export const SET_TILE_DOCKED = 'SET_TILE_DOCKED';
export const RELEASE_GRABBED_TILE = 'RELEASE_GRABBED_TILE';
export const GRAB_TILE = 'GRAB_TILE';
export const UPDATE_BOUNDING_BOX = 'UPDATE_BOUNDING_BOX';
export const INSERT_TILE_BEFORE = 'INSERT_TILE_BEFORE';
