export enum RowActions {
  Update = 'RowActions.Update',
  Remove = 'RowActions.Remove',
  SetOfferQuantity = 'RowActions.SetOfferQuantity',
  SetOfferPrice = 'RowActions.SetOfferPrice',
  SetBidQuantity = 'RowActions.SetBidQuantity',
  SetBidPrice = 'RowActions.SetBidPrice',
  SetRowStatus = 'RowActions.SetRowStatus',
  UpdateOfr = 'RowActions.UpdateOfr',
  UpdateBid = 'RowActions.UpdateBid',
  CreatingOrder = 'RowActions.CreatingOrder',
  OrderCreated = 'RowActions.OrderCreated',
  OrderNotCreated = 'RowActions.OrderNotCreated',
  CancellingOrder = 'RowActions.CancellingOrder',
  OrderCanceled = 'RowActions.OrderCanceled',
  OrderNotCanceled = 'RowActions.OrderNotCanceled',
  SnapshotReceived = 'RowActions.SnapshotReceived',
  GettingSnapshot = 'RowActions.GettingSnapshot',
  ErrorGettingSnapshot = 'RowActions.ErrorGettingSnapshot',
}
