export enum TileActions {
  Initialize = 'TileActions.Initialize',
  SetStrategy = 'TileActions.SetStrategy',
  SetSymbol = 'TileActions.SetSymbol',
  ToggleOCO = 'TileActions.ToggleOCO',
  CancelOrder = 'TileActions.CancelOrder',
  OrderNotCanceled = 'TileActions.OrderNotCanceled',
  OrderCanceled = 'TileActions.OrderCanceled',
  CreateOrder = 'TileActions.CreateOrder',
  OrderNotCreated = 'TileActions.OrderNotCreated',
  OrderCreated = 'TileActions.OrderCreated',
  SnapshotReceived = 'TileActions.SnapshotReceived',
  GettingSnapshot = 'TileActions.GettingSnapshot',
  ErrorGettingSnapshot = 'TileActions.ErrorGettingSnapshot',
  CancelAllOrders = 'TileActions.CancelAllOrders',
  AllOrdersNotCanceled = 'TileActions.AllOrdersNotCanceled',
  AllOrdersCanceled = 'TileActions.AllOrdersCanceled',
}
