export enum TOBActions {
  Initialize = 'TOBActions.Initialize',
  SetStrategy = 'TOBActions.SetStrategy',
  SetSymbol = 'TOBActions.SetSymbol',
  ToggleOCO = 'TOBActions.ToggleOCO',
  CancelOrder = 'TOBActions.CancelOrder',
  OrderNotCanceled = 'TOBActions.OrderNotCanceled',
  OrderCanceled = 'TOBActions.OrderCanceled',
  CreateOrder = 'TOBActions.CreateOrder',
  OrderNotCreated = 'TOBActions.OrderNotCreated',
  OrderCreated = 'TOBActions.OrderCreated',
  SnapshotReceived = 'TOBActions.SnapshotReceived',
  GettingSnapshot = 'TOBActions.GettingSnapshot',
  ErrorGettingSnapshot = 'TOBActions.ErrorGettingSnapshot',
  CancelAllOrders = 'TOBActions.CancelAllOrders',
  AllOrdersNotCanceled = 'TOBActions.AllOrdersNotCanceled',
  AllOrdersCanceled = 'TOBActions.AllOrdersCanceled',
  UpdatingOrder = 'TOBActions.UpdatingOrder',
  OrderUpdated = 'TOBActions.OrderUpdated',
  OrderNotUpdated = 'TOBActions.OrderNotUpdated',
  FetchingOrders = 'TOBActions.FetchingOrders',
  OrdersFetched = 'TOBActions.OrdersFetched',
  OrdersNotFetched = 'TOBActions.OrdersNotFetched',
  UpdateDOB = 'TOBActions.UpdateDOB',
  UpdateOrder = 'TOBActions.UpdateOrder',
  DeleteOrder = 'TOBActions.DeleteOrder',
}
