export enum WorkspaceActions {
  AddWindow = 'WorkspaceActions.AddWindow',
  UpdateGeometry = 'WorkspaceActions.UpdateGeometry',
  RemoveWindow = 'WorkspaceActions.RemoveWindow',
  MinimizeWindow = 'WorkspaceActions.MinimizeWindow',
  RestoreWindow = 'WorkspaceActions.RestoreWindow',
  SetWindowTitle = 'WorkspaceActions.SetWindowTitle',
  BringToFront = 'WorkspaceActions.BringToFront',
  SetWindowAutoSize = 'WorkspaceActions.SetWindowAutoSize',
  Toast = 'WorkspaceActions.Toast',
  ToolbarTryShow = 'WorkspaceActions.ToolbarTryShow',
  ToolbarShow = 'WorkspaceActions.ToolbarShow',
  ToolbarHide = 'WorkspaceActions.ToolbarHide',
  ToolbarTogglePin = 'WorkspaceActions.ToolbarTogglePin',
  LoadingMarkets = 'WorkspaceActions.LoadingMarkets',
  UpdateMarkets = 'WorkspaceActions.UpdateMarkets',
}
